version: '2'
services:
  chef_server:
    container_name: chef_server
    hostname: chef_server
    # https://hub.docker.com/r/chef/chefdk/
    image: chef/chefdk
  chef_client:
    container_name: chef_client
    hostname: chef_client
    # https://hub.docker.com/r/chef/chefdk/
    image: chef/chefdk
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ./config:/tmp/config
      - ./cookbooks:/tmp/cookbooks
